//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeptEmpTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentT
    {
        public int DeptId { get; set; }
        public string DeptName { get; set; }
        public string DeptHOD { get; set; }
        public Nullable<int> DeptInaug { get; set; }
        public string DeptInaugName { get; set; }
        public Nullable<int> PassPerc { get; set; }
    }
}
