//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeptEmpTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeT
    {
        public int EmpID { get; set; }
        public int DId { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> EmpDOB { get; set; }
        public string EmpAddr { get; set; }
        public string EmpDesg { get; set; }
        public string EmpDOJ { get; set; }
    }
}
